name: stash
services:
  app:
    image: stashapp/stash:latest
    network_mode: "service:tailscale"
    restart: unless-stopped
    ports:
      - 9999:9999
    depends_on:
      - tailscale
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"
    environment:
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
      ## Adjust below to change default port (9999)
      - STASH_PORT=9999
    volumes:
      - /etc/localtime:/etc/localtime:ro
      ## Adjust below paths (the left part) to your liking.
      ## E.g. you can change ./config:/root/.stash to ./stash:/root/.stash

      ## Keep configs, scrapers, and plugins here.
      - ${PWD}/config:/root/.stash
      ## Point this at your collection.
      - /mnt/nas/Adult:/data
      ## This is where your stash's metadata lives
      - ${PWD}/metadata:/metadata
      ## Any other cache content.
      - ${PWD}/cache:/cache
      ## Where to store binary blob data (scene covers, images)
      - ${PWD}/blobs:/blobs
      ## Where to store generated content (screenshots,previews,transcodes,sprites)
      - ${PWD}/generated:/generated
