# generated by datamodel-codegen:
#   filename:  migration.graphql
#   timestamp: 2025-09-22T07:36:32+00:00

from __future__ import annotations

from typing import Literal, Optional, TypeAlias

from pydantic import BaseModel, Field

Boolean: TypeAlias = bool
"""
The `Boolean` scalar type represents `true` or `false`.
"""


String: TypeAlias = str
"""
The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.
"""


class MigrateBlobsInput(BaseModel):
    deleteOld: Optional[Boolean] = None
    typename__: Optional[Literal['MigrateBlobsInput']] = Field('MigrateBlobsInput', alias='__typename')


class MigrateSceneScreenshotsInput(BaseModel):
    deleteFiles: Optional[Boolean] = None
    overwriteExisting: Optional[Boolean] = None
    typename__: Optional[Literal['MigrateSceneScreenshotsInput']] = Field(
        'MigrateSceneScreenshotsInput', alias='__typename'
    )
