# generated by datamodel-codegen:
#   filename:  scalars.graphql
#   timestamp: 2025-09-22T06:51:43+00:00

from __future__ import annotations

from typing import TypeAlias

Any: TypeAlias = str


BoolMap: TypeAlias = str
"""
A String -> Boolean map
"""


Boolean: TypeAlias = bool
"""
The `Boolean` scalar type represents `true` or `false`.
"""


Int64: TypeAlias = str


Map: TypeAlias = str
"""
A String -> Any map
"""


PluginConfigMap: TypeAlias = str
"""
A plugin ID -> Map (String -> Any map) map
"""


String: TypeAlias = str
"""
The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.
"""


Time: TypeAlias = str
"""
An RFC3339 timestamp
"""


Timestamp: TypeAlias = str
"""
Timestamp is a point in time. It is always output as RFC3339-compatible time points.
It can be input as a RFC3339 string, or as "<4h" for "4 hours in the past" or ">5m"
for "5 minutes in the future"
"""


Upload: TypeAlias = str
"""
A multipart file upload
"""
