# generated by datamodel-codegen:
#   filename:  version.graphql
#   timestamp: 2025-09-22T07:37:13+00:00

from __future__ import annotations

from typing import Literal, Optional, TypeAlias

from pydantic import BaseModel, Field

Boolean: TypeAlias = bool
"""
The `Boolean` scalar type represents `true` or `false`.
"""


String: TypeAlias = str
"""
The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.
"""


class LatestVersion(BaseModel):
    release_date: String
    shorthash: String
    url: String
    version: String
    typename__: Optional[Literal["LatestVersion"]] = Field("LatestVersion", alias="__typename")


class Version(BaseModel):
    build_time: String
    hash: String
    version: Optional[String] = None
    typename__: Optional[Literal["Version"]] = Field("Version", alias="__typename")
